config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about'
  post 'follow/:id' => 'relationships#follow', as: 'follow' #フォローする
  delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' #フォロー外す

  resources :users, only: [:show,:index,:edit,:update]
  get 'users/:id/followers' => 'relationships#followers', as: 'followers'
  get 'users/:id/followees' => 'relationships#followees', as: 'followees'

  # users/:id/followers
  # users/:id/followees

  resources :books do
		resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books #1対Nの関係になるように記述
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy #イイネ機能
  attachment :profile_image
  #追記
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #フォロワー取得

  has_many :following_user, through: :follower, source: :followed #自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower #自分をフォローしている人
 
  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }

  #追記
#ユーザーをフォローする
 def follow(user_id)
   follower.create(followed_id: user_id)
 end

 #ユーザーのフォローを外す
 def unfollow(user_id)
   follower.find_by(followed_id: user_id).destroy
 end

 # フォローしていればtrueを返す
 def following?(user)
  following_user.include?(user)
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :baria_user, only: [:update, :edit]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
    @user = User.find(params[:id])#追記
  end

  def new
    @user = User.new #新規のユーザーを作成している
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
    @user = current_user

  end

  def edit
  	@user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    @user.save
    flash[:notice] = "Welcome! You have signed up successfully."
  end


  def update
  	@user = User.find(params[:id]) 
    @user.update(user_params)
  if @user.save
  		redirect_to user_path(@user.id), notice: "You have updated user successfully."
  	else
  		render action: :edit
  	end
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

 def current_user?(user)
 	user == current_user
 end
end

app/views/users/ _stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/ show_follower.erb
<% @user.followers.each do |user| %>
<table>
<tr>
  <td>  <%= user.username %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>  

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= @user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= @user.introduction %></th>
		</tr>
</table>

<div class="row">
 <%= link_to edit_user_path(current_user) do %>
 <p class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" ></p> 
<% end %>
</div>

app/views/users/edit.html.erb
<div class="body">
<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>errors prohibited this book from being saved:</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<h2>User info</h2>

<%= form_for(@user) do |f| %>


<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
 <div class="row">
<%= render 'layouts/sidebar' %>
<div class="col-xs-9">
<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, size:"50x50", fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--users一覧 -->
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
 <div class="row">
<%= render 'layouts/sidebar' %>

<div class="col-xs-9">
<h2>Books</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to (book.user) do %>
				<%= attachment_image_tag @user, :profile_image, size:"50x50", format:'jpeg', fallback: "no-image-mini.jpg" %>
				<% end %>
			</td>
			<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
			<td>
				<% if book.favorited_by?(current_user) %>
					
					<%= link_to book_favorites_path(book), method: :delete do %>
					<span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
					<%= book.favorites.count %>
					<% end %>

					<% else %>
                    
					<%= link_to book_favorites_path(book), method: :post do %>
					<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
					<%= book.favorites.count %>
					<% end %>
                    <% end %>
			</td>
		    <td><%= link_to "コメント数：#{book.book_comments.count}", book_path(book.id) %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--books一覧 -->
 </div>
</div>
</div>

app/views/users/show_follow.html.erb
<% @user.followers.each do |user| %>
<table>
<tr>
  <td>  <%= user.username %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>