config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about'
  post 'follow/:id' => 'relationships#follow', as: 'follow' #フォローする
  delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' #フォロー外す

  resources :users, only: [:show,:index,:edit,:update]
  get 'users/:id/followers' => 'relationships#followers', as: 'followers'
  get 'users/:id/followees' => 'relationships#followees', as: 'followees'

  # users/:id/followers
  # users/:id/followees

  resources :books do
		resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	 def favorited_by?(user)
	 	   favorites.where(user_id: user.id).exists?
	 	end
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :corrent_user, only: [:edit, :update]

  def show
    book = Book.new
  	@book = Book.find(params[:id])
    @user = User.find_by(id: @book.user_id)
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new #投稿フォーム
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @user = current_user
  end

  def new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
      flash[:message] = "successfully"
  		redirect_to book_path(@book.id), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
      @user = current_user
  		@books = Book.all
  		render action: :index
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy #削除
    redirect_to books_path #booksへリダイレクト
  end

  def corrent_user
    @book = Book.find(params[:id])
   if @book.user != current_user
    redirect_to books_path
  end
end


  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
      flash[:message] = "successfully"
  		redirect_to book_path
      # notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def delete
  	@book = Book.find(params[:id])
  	@book.destoy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  def corrent_user
    @book = Book.find(params[:id])
   if @book.user != current_user
    redirect_to books_path
  end
end

  private

  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<%= form_for(@book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<!-- エラー文 -->
 <% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
<!-- エラー文 -->


<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
| <%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="container">
 <div class="row">
<%= render 'layouts/sidebar' %>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user.id) do %>
						<%= attachment_image_tag book.user, :profile_image, format:'lpeg', size:"50x50", fallback: "no-image-mini.jpg" %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>

					<td>
					<% if book.favorited_by?(current_user) %>
					
					<%= link_to book_favorites_path(book), method: :delete do %>
					<span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
					<%= book.favorites.count %>
					<% end %>

					<% else %>
                    
					<%= link_to book_favorites_path(book), method: :post do %>
					<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
					<%= book.favorites.count %>
					<% end %>
                    <% end %>	
					</td>
					<td><%= link_to "コメント数：#{book.book_comments.count}", book_path(book.id) %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->
	</div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container"><!--追加-->
 <div class="row">
<%= render 'layouts/sidebar' %>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, size:"50x50", fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>

					<td>
					<% if @book.favorited_by?(current_user) %>
					
					<%= link_to book_favorites_path(@book), method: :delete do %>
					<span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
					<%= @book.favorites.count %>
					<% end %>

					<% else %>
                    
					<%= link_to book_favorites_path(@book), method: :post do %>
					<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
					<%= @book.favorites.count %>
					<% end %>
                    <% end %>
					</td>


					<td>コメント数：<%= @book.book_comments.count %></td>

					<% if @book.user_id == current_user.id %>

					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
				</tr>
			  <% end %>
			  
			</table>

			<% @book.book_comments.each do |book_comment| %>
			<div class="comment-text">
			<%= book_comment.comment %>
		    </div>
			
			<% if user_signed_in? && book_comment.user_id == current_user.id %>
			<%= link_to 'Destroy', book_book_comments_path(book_comment.id), method: :delete %>
			<% end %>
			<% end %>
		

			<!-- form_for -->
				 <%= form_for [@book, @book_comment] do |f| %>
				  <div class="row">
				  	<div class="col-xs-10">
				  	  <%= f.text_area :comment,rows:'5', class:"form-control",placeholder:"コメントをここに" %>
				  	</div>
				  </div>
				  <%= f.submit "送信する" %>
				  <% end %>
                <!-- form_for -->

	</div>
</div>
</div>