config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about'
  post 'follow/:id' => 'relationships#follow', as: 'follow' #フォローする
  delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' #フォロー外す

  resources :users, only: [:show,:index,:edit,:update]
  get 'users/:id/followers' => 'relationships#followers', as: 'followers'
  get 'users/:id/followees' => 'relationships#followees', as: 'followees'

  # users/:id/followers
  # users/:id/followees

  resources :books do
		resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end
end

app/views/layouts/_header.html.erb
    <!--ヘッダーの記述-->
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' Users', "/users", class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' Home', "/", class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <!--ヘッダーの記述-->

app/views/layouts/_sidebar.html.erb
 <div class="col-xs-3">

 <div id="success_explanation">
  <p><%= flash[:message] %></p>
  </div>
  <div class="success_message">
  <p><%= flash[:notice] %></p>
  </div>
  <% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>



<h2>User info</h2>

<!-- User Info -->

<table class="table">
		<tr><%= attachment_image_tag @user, :profile_image, size:'100x100', fallback: "no_image.jpg", size:'100x100' %></tr>

		<tr>
			<th>name</th>
			<th><%= @user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= @user.introduction %></th>
		<tr>
			<th>follows</th>
			<th><%= link_to "#{@user.follower.count}", followers_path(@user) %></th>
		</tr>
		<tr>
			<th>followers</th>
			<th><%= link_to "#{@user.followed.count}", followees_path(@user) %></th>
		</tr>
</table>


<% if @user == current_user %>
	<div class="row">
		<%= link_to edit_user_path(current_user) do %>
			 <p class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" ></p> 
		<% end %>
    </div>
<% else %>
	<% if current_user.following?(@user) %>
	    <%= link_to 'フォロー外す', unfollow_path(@user.id), method: :DELETE, class:"btn btn-primary" %>
	<% else %>
	    <%= link_to 'フォローする', follow_path(@user.id), method: :POST, class:"btn btn-success"%>
	<% end %>
<% end %>

  

<!-- User Info -->


<h2>New book</h2>

<!-- New Book -->
<%= form_for(@book) do |f| %>
	<div class="field row">
		<h4>Title</h4>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<h4>Opinion</h4> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit "Create Book", class: "btn btn-primary col-xs-12 field" %>
	</div>
<% end %>
<!-- New Book -->

 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

     <%= render 'layouts/header' %>
     <%= yield%>
    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->

    </div>
  </body>
</html>